language: node_js
node_js:
- '0.12'
- '0.10'
deploy:
  provider: npm
  email: pascal@bloob.io
  api_key:
    secure: A4AI1TUliX+5WbVMsN+rqb7aitFt/U/SjsjlZs4T+HyxGTK0Az5n+BDEWzt8P6LbpR37H1uZ0cR8QaAoXW10NgdcV6auwr/1OFa1S29i2Q9BHBC1TH2b8NhCYyvmrjB9tw75XXVI94AG2PjCTQ4XokCqNgcs/NO0rpacSx5UgEg=
  on:
    tags: true
env:
  global:
    secure: Hh2Ds3TpEJirBGUiCEXgA2ZCFLRyiINp3xMkaNayavkLJ9wTCHL/pjVyEZwEvZbDFALyiIPPL6uqjz/qMBT/vT4s0gkPcuSZ0eLaolrxm1AMbvhzsMRiQ+e1pRBCeVgQL/46gKyIn6eefvJX2993kIODG0eKR6GA5ZBnfJvw5zU=
